server:
  port: 19092

spring:
  profiles:
    default: dev
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

resilience4j:
  circuitbreaker:
    configs:
      default: # 기본 구성 이름
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s

feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin: # Zipkin 설정 - 필수 과제 - 분산추적 구현해보기
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0