spring:
  datasource:
    url: jdbc:mysql://test.rds.amazonaws.com:3306/msa_exam?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: test
  jpa:
    show-sql: true
